package.name = "core"

[tag.Alias]
args = [ "p1", "p2" ]
desc = "`{p1}` must not have other alias"

[tag.Align]
args = [ "p", "T" ]
desc = "pointer `{p}` must be properly aligned for type `{T}`"

[tag.Alive]
args = [ "p", "l" ]
desc = "the reference of `{p}` must outlive the lifetime `{l}`"

[tag.Allocated]
args = [ "p", "T", "len", "A" ]
desc = "the memory range `[{p}, {p} + sizeof({T})*{len})` must be allocated by allocator `{A}`"

[tag.Deref]
args = [ "p", "T", "len" ]
desc = "pointer `{p}` must be dereferencable in the `sizeof({T})*{len}` memory from it"

[tag.InBound]
args = [ "p", "T", "len" ]
desc = "the pointer `{p}` and its offset up to `sizeof({T})*{len}` must point to a single allocated object"

[tag.Init]
args = [ "p", "T", "len" ]
desc = "the memory range `[{p}, {p} + sizeof({T})*{len}]` must be fully initialized for type `{T}`"

[tag.Layout]
args = [ "p", "layout" ]
desc = "the memory pointed by `{p}` must remain consistent with `{layout}`"

[tag.NoPadding]
args = [ "T" ]
desc = "type `{T}` must have no padding bytes"

[tag.NonNull]
args = [ "p" ]
desc = "pointer `{p}` must not be null"

[tag.NonOverlap]
args = [ "dst", "src", "T", "len" ]
desc = "the memory ranges `[{dst}, {dst} + sizeof({T})*{len})` and `[{src}, {src} + sizeof({T})*{len}]` must not overlap"

[tag.NonVolatile]
args = [ "p", "T", "len" ]
desc = "the memory access of `[{p}, {p} + sizeof({T})*{len}]` must be volatile"

[tag.Opened]
args = [ "fd" ]
desc = "the file descriptor `{fd}` must be valid and open"

[tag.Owning]
args = [ "p" ]
desc = "the pointer `{p}` must hold exclusive ownership of its reference"

[tag.NonOwned]
args = [ "p" ]
desc = "the pointer `{p}` doesn't hold exclusive ownership of its reference"

[tag.Pinned]
args = [ "p", "l" ]
desc = "pointer `{p}` must remain at the same memory address for the duration of lifetime `{l}`"

[tag.Ptr2Ref]
args = [ "p", "T" ]
desc = "the reference conversion of the pointer `{p}` must be valid"

[tag.Size]
args = [ "T", "c" ]
desc = "the size of type `{T}` should be `{c}`"

[tag.Trait]
args = [ "T", "trait", "property" ] # FIXME: extra property compared to primitive-sp doc
desc = "if type `{T}` implements trait `{trait}`, the property `{property}` is mitigated"

[tag.Typed]
args = [ "p", "T" ]
desc = "the pointer `{p}` must point to a value of `{T}`"

[tag.Unreachable]
args = [  ]
desc = "the current program point should not be reachable during execution"

[tag.Unwrap]
args = [ "x", "T", "target" ] # FIXME: extra target compared to desc
desc = "the value `{x}` must be `Some({T})`"

[tag.ValidCStr]
args = [ "p", "len" ]
desc = "the memory range `[{p}, {p} + {len} + 1]` must contain a valid C-style string"

[tag.ValidNum]
args = [ "exp", "vrange" ]
desc = "the value of `{exp}` must lie within the valid `{vrange}`"

[tag.ValidPtr]
args = [ "p", "T", "len" ]
desc = "pointer `{p}` must be valid for reading and writing the `sizeof({T})*{len}` memory from it"

[tag.ValidString]
args = [ "arange" ]
desc = "the memory range `{arange}` must contain valid UTF-8 bytes"

